#!/usr/bin/env python3
"""
Render the repo-level license data into the README.md table section.

Reads data/licenses_output.csv (one row per tracked/base HF repo) and replaces
everything between <!-- LICENSE_TABLE_START --> and <!-- LICENSE_TABLE_END -->
in README.md. Tracked repos are grouped by model family; base models (used for
derivative tracing) are listed in a separate section. Stdlib only.

Tables are emitted as GFM (GitHub Flavored Markdown). GitHub's README sanitizer
strips <colgroup>/column-width attributes and target="_blank", so fixed column
widths and "open in new tab" are impossible inside README.md. For those
features, use the GitHub Pages view generated by generate_pages.py (linked at
the top of the table block).
"""
from __future__ import annotations

import csv
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_FILE = ROOT / "data" / "licenses_output.csv"
README = ROOT / "README.md"
START = "<!-- LICENSE_TABLE_START -->"
END = "<!-- LICENSE_TABLE_END -->"
PAGES_URL = "https://bradpita.github.io/Zaokaa-License-Database/"

FAMILY_ORDER = [
    "Wan", "FLUX", "Krea", "Qwen-Image", "Qwen-TTS", "Qwen-VL",
    "Qwen3-LLM", "Qwen", "Gemma", "LTX-Video",
    "Z-Image", "Bernini", "SCAIL", "SeedVR", "Segment Anything",
    "LivePortrait", "Pose", "PoseStudio", "Audio", "Anima", "Kaloscope",
]

TRACKED_HEADERS = ["Model", "Provider", "License", "Commercial", "Commercial terms", "Files", "Downloads", "Updated"]
TRACKED_ALIGNS = ["left", "left", "left", "center", "left", "right", "right", "left"]
BASE_HEADERS = ["Base model", "Provider", "License", "Commercial", "Commercial terms", "Updated"]
BASE_ALIGNS = ["left", "left", "left", "center", "left", "left"]

COMM_EMOJI = {"Yes": "Yes", "No": "No", "Review": "Review"}


def cell_escape(s):
    return (str(s or "")
            .replace("\r", " ")
            .replace("\n", " ")
            .replace("|", "\\|")
            .replace("[", "\\[")
            .replace("]", "\\]")
            .strip())


def md_link(url, text):
    return "[{}]({})".format(cell_escape(text), url.strip())


def fmt_date(s):
    s = str(s or "").strip()
    return s[:10] if s else "-"


def fmt_int(s):
    s = str(s or "").strip()
    return format(int(s), ",") if s.isdigit() else "-"


def model_cell(r):
    name = cell_escape(r.get("name"))
    hf_id = (r.get("hf_id") or "").strip()
    status = r.get("status", "")
    if status == "ok" and hf_id:
        return md_link("https://huggingface.co/" + hf_id, r.get("name"))
    if status == "not_found":
        return name + " - _not found on Hub_"
    return name


def license_cell(r):
    lic = cell_escape(r.get("license")) or "-"
    link_url = (r.get("license_url") or "").strip()
    if lic != "-" and link_url:
        return md_link(link_url, r.get("license"))
    return lic


def comm_cell(r):
    return COMM_EMOJI.get((r.get("commercial_use") or "").strip(), "Review")


def terms_cell(r):
    return cell_escape(r.get("commercial_terms")) or "-"


def md_table(headers, aligns, rows):
    sep = []
    for a in aligns:
        if a == "right":
            sep.append("---:")
        elif a == "center":
            sep.append(":---:")
        else:
            sep.append(":---")
    lines = ["| " + " | ".join(headers) + " |",
             "| " + " | ".join(sep) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return lines


def family_section(tracked):
    lines = []
    by_fam = {}
    for r in tracked:
        by_fam.setdefault(r.get("family", "Other"), []).append(r)
    order = FAMILY_ORDER + sorted(f for f in by_fam if f not in FAMILY_ORDER)
    for fam in order:
        group = by_fam.get(fam)
        if not group:
            continue
        group.sort(key=lambda r: r.get("name", ""))
        lines.append("### {}".format(fam))
        lines.append("")
        rows = []
        for r in group:
            rows.append([
                model_cell(r), cell_escape(r.get("provider")), license_cell(r),
                comm_cell(r), terms_cell(r), fmt_int(r.get("file_count")),
                fmt_int(r.get("downloads")), fmt_date(r.get("last_modified")),
            ])
        lines.extend(md_table(TRACKED_HEADERS, TRACKED_ALIGNS, rows))
        lines.append("")
    return lines


def base_section(base_rows):
    lines = []
    if not base_rows:
        return lines
    lines.append("### Base model declarations (for derivative tracing)")
    lines.append("")
    lines.append("> Original models that derivatives trace up to. Marked per each model's own declaration.")
    lines.append("")
    base_rows.sort(key=lambda r: r.get("name", ""))
    rows = []
    for r in base_rows:
        rows.append([
            model_cell(r), cell_escape(r.get("provider")), license_cell(r),
            comm_cell(r), terms_cell(r), fmt_date(r.get("last_modified")),
        ])
    lines.extend(md_table(BASE_HEADERS, BASE_ALIGNS, rows))
    lines.append("")
    return lines


def build_block(rows):
    lines = []
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    tracked = [r for r in rows if r.get("kind") != "base"]
    base = [r for r in rows if r.get("kind") == "base"]
    lines.append("_Last updated: {} | {} tracked repos + {} base models_".format(ts, len(tracked), len(base)))
    lines.append("")
    if not rows:
        lines.append("> _No data yet. Run `python scripts/fetch_licenses.py` then "
                     "`python scripts/generate_readme.py` (or trigger the GitHub "
                     "Actions workflow) to populate this table._")
        return lines
    lines.append("> **[View the formatted table online]({})** - fixed column widths for "
                 "side-by-side comparison and every link opens in a new tab "
                 "(not possible inside GitHub's README).".format(PAGES_URL))
    lines.append("")
    lines.append("## Tracked models")
    lines.append("")
    lines.extend(family_section(tracked))
    lines.extend(base_section(base))
    return lines


def load_rows():
    if not CSV_FILE.exists():
        return []
    with CSV_FILE.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def main():
    if not README.exists():
        print("README.md not found.", file=sys.stderr)
        return 1
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print("Table markers not found in README.md", file=sys.stderr)
        return 1
    rows = load_rows()
    block = "\n".join(build_block(rows))
    pre = text[:text.index(START) + len(START)]
    post = text[text.index(END):]
    README.write_text(pre + "\n" + block + "\n" + post, encoding="utf-8")
    print("README updated with {} repos.".format(len(rows)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
